var sqlMap = {
    getTokenFromLogin: 'SELECT token FROM littleAnt_user WHERE email = ? and password = ?',
    getUserInfo: 'SELECT * FROM littleAnt_user WHERE token = ?',
    getUserInfoById: 'SELECT * FROM littleAnt_user WHERE id = ?',
    updateUserRole: 'UPDATE littleAnt_user SET role = ?, plan_startdate = ? WHERE storage_number = ?',
    getAllUser: 'SELECT a.*, b.alias FROM littleAnt_user a INNER JOIN littleAnt_rate_table b ON a.rateTable_id = b.id',
    insertPackageItems: 'INSERT INTO littleAnt_user_report_items(package_id,type,item_name,price,unit,brand) VALUES(?,?,?,?,?,?)',
    insertUserPackage: 'INSERT littleAnt_user_package(user_id,litlleant_tracking_number,created_at,package_description,package_comment,total,to_name,to_country_code,to_phone,to_identity_card,to_address,to_city,to_state,to_zip,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',
    insertThirdPartyPackage: 'INSERT INTO littleAnt_third_party_package(user_id,user_defined_tracking,courier,status,in_store_date) VALUES(?,?,?,?,?)',
    insertAdminReportItems: 'INSERT INTO littleAnt_admin_report_items(third_party_packageId,item_name,item_count,pic1_url,pic1_name,pic2_url,pic2_name,pic3_url,pic3_name) VALUES(?,?,?,?,?,?,?,?,?)',
    updateThirdPartyPackage: 'UPDATE littleAnt_third_party_package SET user_id = ?, user_defined_tracking = ?, courier = ?, in_store_date = ? WHERE id = ?',
    updateReportItems: 'UPDATE littleAnt_admin_report_items SET item_name = ?, item_count = ?, pic1_url = ?, pic1_name = ?, pic2_url = ?, pic2_name = ?, pic3_url = ?, pic3_name = ? WHERE id = ?',
    deleteThirdPartyPackagebyId: 'DELETE FROM littleAnt_third_party_package where id=?',
    getAllWaitPackage: "SELECT a.*, b.storage_number, b.role, b.rateTable_id FROM littleant_user_package a INNER JOIN littleant_user b ON a.user_id = b.id WHERE a.status != '已处理' order by id desc",
    getAllFinishPackage: "SELECT a.*, b.storage_number, b.role FROM littleant_user_package a INNER JOIN littleant_user b ON a.user_id = b.id WHERE a.status = '已处理' order by id desc",
    getPackageInfoById: 'SELECT a.*, b.storage_number, b.role,b.balance FROM littleant_user_package a INNER JOIN littleant_user b ON a.user_id = b.id WHERE a.id = ? order by id desc',
    getAllThirdPartyPackage: "SELECT a.id,a.user_id,a.user_defined_tracking,a.courier,a.in_store_date,a.status,b.storage_number,b.email,b.name FROM littleAnt_third_party_package a INNER JOIN littleAnt_user b ON a.user_id = b.id where status != '已全部打包' order by id desc",
    getThirdPartyPackageByUser: 'SELECT * FROM littleAnt_third_party_package WHERE user_id = ? AND status = ? order by id desc',
    updateAdminReportItems: 'UPDATE littleAnt_admin_report_items SET package_Id = ? WHERE id = ?',
    updateThirdPartyPackageStatus: 'UPDATE littleAnt_third_party_package SET status = ?, package_Id = ? WHERE id=?',
    getUserPackageByUser: 'SELECT * FROM littleAnt_user_package WHERE user_id = ? order by id desc',
    existUserPackageByLittleAntTracking: 'select id,finishprocess_time from littleAnt_user_package where litlleant_tracking_number = ? limit 1',
    existStorageNumber: 'select 1 from littleAnt_user where storage_number = ? limit 1',
    existRecipient: 'select 1 from littleAnt_recipients where name = ? and phone = ? and address = ? limit 1',
    existUserEmailOrPhone: 'select 1 from littleAnt_user where email = ? or user_phone = ? limit 1',
    existUserPhone: 'select storage_number from littleAnt_user where user_phone = ? limit 1',
    getItemsByPackageId: 'SELECT * FROM littleAnt_admin_report_items WHERE third_party_packageId = ? AND package_Id IS NULL',
    getUserReportItemsByPackageId: 'SELECT * FROM littleAnt_user_report_items WHERE package_Id = ?',
    getItemsInPackage: 'SELECT * FROM littleAnt_admin_report_items WHERE package_Id = ?',
    getPackageById: 'SELECT * FROM littleAnt_user_package WHERE id = ?',
    getAllRecipients: 'SELECT a.*, b.storage_number FROM littleAnt_recipients a INNER JOIN littleant_user b ON a.user_id = b.id',
    getRecipientsByUser: 'SELECT * FROM littleAnt_recipients WHERE user_id = ?',
    updateRecipientbyId: 'UPDATE littleAnt_recipients SET name = ?,country_code = ?,phone = ?,identity_card = ?,address = ?,city = ?,state = ?,zip = ? WHERE id = ?',
    insertRecipient: 'INSERT INTO littleAnt_recipients (user_id,name,country_code,phone,identity_card,address,city,state,zip) VALUES(?,?,?,?,?,?,?,?,?)',
    deleteRecipientbybyId: 'DELETE FROM littleAnt_recipients where id=?',
    getRecipientbybyId: 'SELECT * FROM littleAnt_recipients WHERE id = ?',
    getVendorTrackingByLittleAntNo: 'SELECT vendor_tracking_number,vendor FROM littleAnt_user_package WHERE litlleant_tracking_number = ?',
    setPackageWeightandStatus: 'UPDATE littleAnt_user_package SET status = ?, total_weight = ?, total_price = ?, finishprocess_time = ? WHERE id = ?',
    updateUserBalance: 'UPDATE littleAnt_user SET balance = balance + ? WHERE storage_number = ?',
    insertUserInvoice: 'INSERT INTO littleAnt_user_invoice(invoice_type,total,user_sotrageNm,tracking_number,memo,created_at) VALUES(?,?,?,?,?,?)',
    registerUser: 'INSERT INTO littleAnt_user(storage_number,email,password,token,role,name,user_phone) VALUES(?,?,?,?,?,?,?)',
    updatePassword: 'UPDATE littleAnt_user SET password = ? WHERE storage_number  = ?',
    getInvoiceByUser: 'SELECT * FROM littleAnt_user_invoice WHERE user_sotrageNm = ? order by id desc',
    getAllInvoices: 'SELECT * FROM littleAnt_user_invoice order by id desc',
    getDefinedTrackingById: 'SELECT user_defined_tracking, status FROM littleant_third_party_package WHERE id = ?',
    deletePackagebybyId: 'DELETE FROM littleAnt_user_package where id=?',
    deleteUserReportItem: 'DELETE FROM littleAnt_user_report_items where id=?',

    //修改包裹信息
    updatePackageDescription: 'UPDATE littleAnt_user_package SET package_description = ?, package_comment = ? WHERE id = ?',
    updatePackageRecipient: 'UPDATE littleAnt_user_package SET to_name = ?,to_country_code = ?,to_phone = ?,to_identity_card = ?,to_address = ?,to_city = ?,to_state = ?,to_zip = ? WHERE id = ?',
    updateUserReportItems: 'UPDATE littleAnt_user_report_items SET type = ?,item_name = ?,price = ?,unit = ?,brand = ? WHERE id = ?',
  }
  
  module.exports = sqlMap;